# Generated by Django 5.2.5 on 2025-09-03 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('t-shirt', 'T-shirt'), ('ball', 'Ball'), ('scarf', 'Scarf'), ('tracksuit', 'Tracksuit')], default='t-shirt', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('item_views', models.PositiveIntegerField(default=0)),
                ('brand', models.CharField(max_length=255)),
                ('release_year', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
