# Generated by Django 5.2.5 on 2025-09-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year of product release (e.g. 2024)', null=True),
        ),
    ]
